version: "3"

services:
  app:
    container_name: laravel
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  web:
    container_name: laravel_nginx
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 8990:80

  database:
    container_name: laravel_mysql
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 8991:3306

  cache:
    container_name: laravel_redis
    image: redis:3.0-alpine

volumes:
  dbdata:
